# Generated by Django 5.1.3 on 2024-12-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
